### 4. 미로 탈출(3시간 남짓 걸림)

- BFS

In [69]:
from collections import deque

def solution(graph, x, y):
    q=deque([ (x,y) ])
    
    graph[x][y]=0 # 방문처리
    count=1 # 방문한 수
    
    dx=[-1,1,0,0]
    dy=[0,0,-1,1] # 상하좌우
    
    while q:
        nx, ny=q.popleft() # 탐색 시작
        print('***********탐색:',nx,ny,'************')
        
        if nx==(N-1) and ny==(M-1): # 도착?
            print('도착',nx,ny)
            count+=1
            break
            
        print('--------(',nx,ny,') 상하좌우 탐색---------')
        
        out=0 # 아웃 카운트
        for i in range(4):   
            mx=nx+dx[i]
            my=ny+dy[i]
            #print('인접노드',mx,my)
            if mx==len(graph)-1 and my==len(graph[0])-1:
                print(mx,my,'는 목적지')
                return count+1
            
            if mx<0 or mx>=N or my<0 or my>=M:
                #print('틀 벗어남',mx,my,out+1)
                print()
                out+=1
                if out==4:
                    print('막다름',count-1)
                    count-=1
                continue
                
            if graph[mx][my]==1:
                q.append( (mx,my) ) # 삽입
                graph[mx][my]=0 # 방문처리
                print(mx,my,'방문처리',count+1)
                count+=1
            else: # 틀 안이지만 괴물
                #print('틀 안이지만 괴물',mx,my,out+1)
                out+=1
                if out==4:
                    print('막다름',count-1)
                    count-=1
                continue
                
            print()
                
    return count

maze=[] # 지도

N,M=map(int,input().split()) # 행, 열

for _ in range(N):
    maze.append(list(map(int,input())))
    
    
solution(maze, 0, 0)
    
# 1. 탐색 시작노드 큐에 삽입 후 방문처리
# 2. 큐에서 노드 꺼내 해당 노드의 인접노드 중 미방문 노드 큐에 삽입 후 방문처리
# 3. 2번 반복

5 6
101010
111111
000001
111111
111111
***********탐색: 0 0 ************
--------( 0 0 ) 상하좌우 탐색---------

1 0 방문처리 2


***********탐색: 1 0 ************
--------( 1 0 ) 상하좌우 탐색---------

1 1 방문처리 3

***********탐색: 1 1 ************
--------( 1 1 ) 상하좌우 탐색---------
1 2 방문처리 4

***********탐색: 1 2 ************
--------( 1 2 ) 상하좌우 탐색---------
0 2 방문처리 5

1 3 방문처리 6

***********탐색: 0 2 ************
--------( 0 2 ) 상하좌우 탐색---------

막다름 5
***********탐색: 1 3 ************
--------( 1 3 ) 상하좌우 탐색---------
1 4 방문처리 6

***********탐색: 1 4 ************
--------( 1 4 ) 상하좌우 탐색---------
0 4 방문처리 7

1 5 방문처리 8

***********탐색: 0 4 ************
--------( 0 4 ) 상하좌우 탐색---------

막다름 7
***********탐색: 1 5 ************
--------( 1 5 ) 상하좌우 탐색---------
2 5 방문처리 8


***********탐색: 2 5 ************
--------( 2 5 ) 상하좌우 탐색---------
3 5 방문처리 9


***********탐색: 3 5 ************
--------( 3 5 ) 상하좌우 탐색---------
4 5 는 목적지

10

- DFS

In [80]:
maze=[] # 지도

N,M=map(int,input().split()) # 행, 열

for _ in range(N):
    maze.append(list(map(int,input())))
    
count=1
    
def solution(graph,x,y):
    if graph[len(graph)-1][len(graph[0])-1]==0:
        print('목적지에 이미 도달함')
        return 0
    
    stack=[(x,y)]
    graph[x][y]=0 # 방문처리
    global count
    dx=[-1,1,0,0]
    dy=[0,0,-1,1] # 상하좌우
    
    while stack:
        if graph[len(graph)-1][len(graph[0])-1]==0:
                    print('도착해서 쫑낼게여')
                    return 0
                
        out=0
        nx, ny=stack.pop() # 탐색 시작
        print('***********탐색:',nx,ny,'************')
        
        if nx==(N-1) and ny==(M-1): # 도착?
            print('도착',nx,ny)
            break
            
        print('--------(',nx,ny,') 상하좌우 탐색---------')
        
        for i in range(4):
            if graph[len(graph)-1][len(graph[0])-1]==0:
                    print('도착해서 쫑낼게여')
                    return 0

            mx=nx+dx[i]
            my=ny+dy[i]
            
            print(nx,ny,'의 인접노드',mx,my)
            
            if mx<0 or mx>=N or my<0 or my>=M:
                print('틀 벗어남',mx,my)
                print()
                out+=1
                print('현재 out',out)
                if out==4:
                    print('막다름')
                    count-=1
                    break
                continue
                
            if graph[mx][my]==1:
                stack.append( (mx,my) ) # 삽입
                graph[mx][my]=0 # 방문처리
                print(mx,my,'방문처리 후 탐색 시작, 현재 방문 수는',count+1)
                count+=1
                solution(graph,mx,my)
            else: # 틀 안이지만 괴물
                print('틀 안이지만 괴물',mx,my)
                out+=1
                print('현재 out',out)
                if out==4:
                    print('막다름. 줄인 카운트는',count-1)
                    count-=1 # 방문 무효
                    break
                continue
        
        print(nx,ny,'에 대한 함수 종료-------------')
                
    return

solution(maze,0,0)
#print(count)
pd.DataFrame(maze)

5 6
101010
111111
000001
111111
111111
***********탐색: 0 0 ************
--------( 0 0 ) 상하좌우 탐색---------
0 0 의 인접노드 -1 0
틀 벗어남 -1 0

현재 out 1
0 0 의 인접노드 1 0
1 0 방문처리 후 탐색 시작, 현재 방문 수는 2
***********탐색: 1 0 ************
--------( 1 0 ) 상하좌우 탐색---------
1 0 의 인접노드 0 0
틀 안이지만 괴물 0 0
현재 out 1
1 0 의 인접노드 2 0
틀 안이지만 괴물 2 0
현재 out 2
1 0 의 인접노드 1 -1
틀 벗어남 1 -1

현재 out 3
1 0 의 인접노드 1 1
1 1 방문처리 후 탐색 시작, 현재 방문 수는 3
***********탐색: 1 1 ************
--------( 1 1 ) 상하좌우 탐색---------
1 1 의 인접노드 0 1
틀 안이지만 괴물 0 1
현재 out 1
1 1 의 인접노드 2 1
틀 안이지만 괴물 2 1
현재 out 2
1 1 의 인접노드 1 0
틀 안이지만 괴물 1 0
현재 out 3
1 1 의 인접노드 1 2
1 2 방문처리 후 탐색 시작, 현재 방문 수는 4
***********탐색: 1 2 ************
--------( 1 2 ) 상하좌우 탐색---------
1 2 의 인접노드 0 2
0 2 방문처리 후 탐색 시작, 현재 방문 수는 5
***********탐색: 0 2 ************
--------( 0 2 ) 상하좌우 탐색---------
0 2 의 인접노드 -1 2
틀 벗어남 -1 2

현재 out 1
0 2 의 인접노드 1 2
틀 안이지만 괴물 1 2
현재 out 2
0 2 의 인접노드 0 1
틀 안이지만 괴물 0 1
현재 out 3
0 2 의 인접노드 0 3
틀 안이지만 괴물 0 3
현재 out 4
막다름. 줄인 카운트는 4
0 2 에 대한 함수 종료-------------
1 2 의 인접노드 2 2
틀 안이지만 괴물 2 2
현재 out 1
1 2 의 인접노드 1 1
틀 안이지만 괴물 1 1
현재 out 2
1 2 의 인접노드 1 3
1 3 방문처리 후 탐색 시작, 현재 방문 수는 5
***********탐색: 1 3 ************
--------( 1 3 ) 상하좌우 탐색---------
1 3 의 인접노드 0 3
틀 안이지만 괴물 0 3
현재 out 1
1 3 의 인접노드 2 3
틀 안이지만 괴물 2 3
현재 out 2
1 3 의 인접노드 1 2
틀 안이지만 괴물 1 2
현재 out 3
1 3 의 인접노드 1 4
1 4 방문처리 후 탐색 시작, 현재 방문 수는 6
***********탐색: 1 4 ************
--------( 1 4 ) 상하좌우 탐색---------
1 4 의 인접노드 0 4
0 4 방문처리 후 탐색 시작, 현재 방문 수는 7
***********탐색: 0 4 ************
--------( 0 4 ) 상하좌우 탐색---------
0 4 의 인접노드 -1 4
틀 벗어남 -1 4

현재 out 1
0 4 의 인접노드 1 4
틀 안이지만 괴물 1 4
현재 out 2
0 4 의 인접노드 0 3
틀 안이지만 괴물 0 3
현재 out 3
0 4 의 인접노드 0 5
틀 안이지만 괴물 0 5
현재 out 4
막다름. 줄인 카운트는 6
0 4 에 대한 함수 종료-------------
1 4 의 인접노드 2 4
틀 안이지만 괴물 2 4
현재 out 1
1 4 의 인접노드 1 3
틀 안이지만 괴물 1 3
현재 out 2
1 4 의 인접노드 1 5
1 5 방문처리 후 탐색 시작, 현재 방문 수는 7
***********탐색: 1 5 ************
--------( 1 5 ) 상하좌우 탐색---------
1 5 의 인접노드 0 5
틀 안이지만 괴물 0 5
현재 out 1
1 5 의 인접노드 2 5
2 5 방문처리 후 탐색 시작, 현재 방문 수는 8
***********탐색: 2 5 ************
--------( 2 5 ) 상하좌우 탐색---------
2 5 의 인접노드 1 5
틀 안이지만 괴물 1 5
현재 out 1
2 5 의 인접노드 3 5
3 5 방문처리 후 탐색 시작, 현재 방문 수는 9
***********탐색: 3 5 ************
--------( 3 5 ) 상하좌우 탐색---------
3 5 의 인접노드 2 5
틀 안이지만 괴물 2 5
현재 out 1
3 5 의 인접노드 4 5
4 5 방문처리 후 탐색 시작, 현재 방문 수는 10
목적지에 이미 도달함
도착해서 쫑낼게여
도착해서 쫑낼게여
도착해서 쫑낼게여
1 4 에 대한 함수 종료-------------
도착해서 쫑낼게여
1 3 에 대한 함수 종료-------------
도착해서 쫑낼게여
1 2 에 대한 함수 종료-------------
도착해서 쫑낼게여
1 1 에 대한 함수 종료-------------
도착해서 쫑낼게여
1 0 에 대한 함수 종료-------------
도착해서 쫑낼게여
도착해서 쫑낼게여

   0  1  2  3  4  5
0  0  0  0  0  0  0
1  0  0  0  0  0  0
2  0  0  0  0  0  0
3  1  1  1  1  1  0
4  1  1  1  1  1  0

- 답안 예시

In [79]:
from collections import deque

n,m= map(int,input().split())
graph=[]

for i in range(n):
    graph.append(list(map(int,input())))
    
dx=[-1,1,0,0]
dy=[0,0,-1,1]

def bfs(x,y):
    queue=deque()
    queue.append((x,y))
    
    while queue:
        x,y=queue.popleft()
        
        for i in range(4):
            nx=x+dx[i]
            ny=y+dy[i]
            
            if nx<0 or ny<0 or nx>=n or ny>=m:
                continue
                
            if graph[nx][ny]==0:
                continue
                
            if graph[nx][ny]==1:
                graph[nx][ny]=graph[x][y]+1
                queue.append((nx,ny))
                
    return graph[n-1][m-1]

bfs(0,0)

pd.DataFrame(graph)

5 6
101010
111111
000001
111111
111111

    0   1   2   3   4   5
0   3   0   5   0   7   0
1   2   3   4   5   6   7
2   0   0   0   0   0   8
3  14  13  12  11  10   9
4  15  14  13  12  11  10

---

In [78]:
test=[[1,2,3],[4,5,6]]
test2=test.copy()

pd.DataFrame(test)

   0  1  2
0  1  2  3
1  4  5  6